language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jplinardon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jplinardon/docker-react npm run test